---@class TES3MP
local api

---Generate a random string of a particular length that only contains letters and numbers.
---@param length integer @The length of the generated string.
---@return string @The generated string.
function api.GenerateRandomString(length) end

---Get the SHA256 hash corresponding to an input string.
---@param inputString string @The input string.
---@return string @The SHA256 hash.
function api.GetSHA256Hash(inputString) end

---Get the last player ID currently connected to the server.
---@return integer @The player ID.
function api.GetLastPlayerId() end

---Get the current (latest) mpNum generated by the server.
---
---Every object that did not exist in an .ESM or .ESP data file and has instead been placed or spawned through a server-sent packet has a numerical index known as its mpNum.
---
---When ObjectPlace and ObjectSpawn packets are received from players, their objects lack mpNums, so the server assigns them some based on incrementing the server's current mpNum, with the operation's final mpNum becoming the server's new current mpNum.
---@return integer @The mpNum.
function api.GetCurrentMpNum() end

---Set the current (latest) mpNum generated by the server.
---
---When restarting a server, it is important to revert to the previous current (latest) mpNum as stored in the server's data, so as to avoid starting over from 0 and ending up assigning duplicate mpNums to objects.
---@param mpNum integer @The number that should be used as the new current mpNum.
function api.SetCurrentMpNum(mpNum) end
