-- This file is used to track and simplify dealing with all enumerations
-- currently implemented in packets

enumerations = {}
enumerations.ai = { CANCEL = 0, ACTIVATE = 1, COMBAT = 2, ESCORT = 3, FOLLOW = 4, TRAVEL = 5, WANDER = 6 }
enumerations.aiPrintableAction = { CANCEL = "cancelling current AI", ACTIVATE = "activating",
    COMBAT = "initiating combat with", ESCORT = "escorting", FOLLOW = "following", TRAVEL = "travelling to",
    WANDER = "wandering" }
enumerations.container = { SET = 0, ADD = 1, REMOVE = 2, REQUEST = 3 }
enumerations.containerSub = { NONE = 0, DRAG = 1, DROP = 2, TAKE_ALL = 3, REPLY_TO_REQUEST = 4, RESTOCK_RESULT = 5 }
enumerations.dialogueChoice = { TOPIC = 0, PERSUASION = 1, COMPANION_SHARE = 2, BARTER = 3, SPELLS = 4, TRAVEL = 5, 
    SPELLMAKING = 6, ENCHANTING = 7, TRAINING = 8, REPAIR = 9 }
enumerations.doorstate = { OPEN = 1, CLOSED = 2 }
enumerations.drawstate = { NONE = 0, WEAPON = 1, SPELL = 2 }
enumerations.effects = { WATER_BREATHING = 0, SWIFT_SWIM = 1, WATER_WALKING = 2, SHIELD = 3, FIRE_SHIELD = 4, 
    LIGHTNING_SHIELD = 5, FROST_SHIELD = 6, BURDEN = 7, FEATHER = 8, JUMP = 9, LEVITATE = 10, SLOW_FALL = 11, LOCK = 12, 
    OPEN = 13, FIRE_DAMAGE = 14, SHOCK_DAMAGE = 15, FROST_DAMAGE = 16, DRAIN_ATTRIBUTE = 17, DRAIN_HEALTH = 18, 
    DRAIN_MAGICKA = 19, DRAIN_FATIGUE = 20, DRAIN_SKILL = 21, DAMAGE_ATTRIBUTE = 22, DAMAGE_HEALTH = 23, 
    DAMAGE_MAGICKA = 24, DAMAGE_FATIGUE = 25, DAMAGE_SKILL = 26, POISON = 27, WEAKNESS_FIRE = 28, WEAKNESS_FROST = 29, 
    WEAKNESS_SHOCK = 30, WEAKNESS_MAGICKA = 31, WEAKNESS_COMMON_DISEASE = 32, WEAKNESS_BLIGHT_DISEASE = 33, 
    WEAKNESS_CORPRUS_DISEASE = 34, WEAKNESS_POISON = 35, WEAKNESS_NORMAL_WEAPONS = 36, DISINTEGRATE_WEAPON = 37, 
    DISINTEGRATE_ARMOR = 38, INVISIBILITY = 39, CHAMELEON = 40, LIGHT = 41, SANCTUARY = 42, NIGHTEYE = 43, CHARM = 44, 
    PARALYZE = 45, SILENCE = 46, BLIND = 47, SOUND = 48, CALM_HUMANOID = 49, CALM_CREATURE = 50, FRENZY_HUMANOID = 51, 
    FRENZY_CREATURE = 52, DEMORALIZE_HUMANOID = 53, DEMORALIZE_CREATURE = 54, RALLY_HUMANOID = 55, RALLY_CREATURE = 56, 
    DISPEL = 57, SOULTRAP = 58, TELEKINESIS = 59, MARK = 60, RECALL = 61, DIVINE_INTERVENTION = 62, 
    ALMSIVI_INTERVENTION = 63, DETECT_ANIMAL = 64, DETECT_ENCHANTMENT = 65, DETECT_KEY = 66, SPELL_ABSORPTION = 67, 
    REFLECT = 68, CURE_COMMON_DISEASE = 69, CURE_BLIGHT_DISEASE = 70, CURE_CORPRUS_DISEASE = 71, CURE_POISON = 72, 
    CURE_PARALYZATION = 73, RESTORE_ATTRIBUTE = 74, RESTORE_HEALTH = 75, RESTORE_MAGICKA = 76, RESTORE_FATIGUE = 77, 
    RESTORE_SKILL = 78, FORTIFY_ATTRIBUTE = 79, FORTIFY_HEALTH = 80, FORTIFY_MAGICKA = 81, FORTIFY_FATIGUE = 82, 
    FORTIFY_SKILL = 83, FORTIFY_MAXIMUM_MAGICKA = 84, ABSORB_ATTRIBUTE = 85, ABSORB_HEALTH = 86, ABSORB_MAGICKA = 87, 
    ABSORB_FATIGUE = 88, ABSORB_SKILL = 89, RESIST_FIRE = 90, RESIST_FROST = 91, RESIST_SHOCK = 92, RESIST_MAGICKA = 93, 
    RESIST_COMMON_DISEASE = 94, RESIST_BLIGHT_DISEASE = 95, RESIST_CORPRUS_DISEASE = 96, RESIST_POISON = 97, 
    RESIST_NORMAL_WEAPONS = 98, RESIST_PARALYSIS = 99, REMOVE_CURSE = 100, TURN_UNDEAD = 101, SUMMON_SCAMP = 102, 
    SUMMON_CLANNFEAR = 103, SUMMON_DAEDROTH = 104, SUMMON_DREMORA = 105, SUMMON_ANCESTRAL_GHOST = 106, 
    SUMMON_SKELETAL_MINION = 107, SUMMON_BONEWALKER = 108, SUMMON_GREATER_BONEWALKER = 109, SUMMON_BONELORD = 110, 
    SUMMON_WINGED_TWILIGHT = 111, SUMMON_HUNGER = 112, SUMMON_GOLDEN_SAINT = 113, SUMMON_FLAME_ATRONACH = 114, 
    SUMMON_FROST_ATRONACH = 115, SUMMON_STORM_ATRONACH = 116, FORTIFY_ATTACK = 117, COMMAND_CREATURE = 118, 
    COMMAND_HUMANOID = 119, BOUND_DAGGER = 120, BOUND_LONGSWORD = 121, BOUND_MACE = 122, BOUND_BATTLE_AXE = 123, 
    BOUND_SPEAR = 124, BOUND_LONGBOW = 125, EXTRASPELL = 126, BOUND_CUIRASS = 127, BOUND_HELM = 128, BOUND_BOOTS = 129, 
    BOUND_SHIELD = 130, BOUND_GLOVES = 131, CORPRUS = 132, VAMPIRISM = 133, SUMMON_CENTURION_SPHERE = 134, SUN_DAMAGE = 135, 
    STUNTED_MAGICKA = 136, SUMMON_FABRICANT = 137, CALL_WOLF = 138, CALL_BEAR = 139, SUMMON_BONEWOLF = 140, 
    S_EFFECT_SUMMON_CREATURE04 = 141, S_EFFECT_SUMMON_CREATURE05 = 142 }
enumerations.equipment = { HELMET = 0, CUIRASS = 1, GREAVES = 2, LEFT_PAULDRON = 3, RIGHT_PAULDRON = 4, 
    LEFT_GAUNTLET = 5, RIGHT_GAUNTLET = 6, BOOTS = 7, SHIRT = 8, PANTS = 9, SKIRT = 10, ROBE = 11, LEFT_RING = 12,
    RIGHT_RING = 13, AMULET = 14, BELT = 15, CARRIED_RIGHT = 16, CARRIED_LEFT = 17, AMMUNITION = 18 }
enumerations.faction = { RANK = 0, EXPULSION = 1, REPUTATION = 2 }
enumerations.inventory = { SET = 0, ADD = 1, REMOVE = 2 }
enumerations.journal = { ENTRY = 0, INDEX = 1 }
enumerations.log = { VERBOSE = 0, INFO = 1, WARN = 2, ERROR = 3, FATAL = 4 }
enumerations.miscellaneous = { MARK_LOCATION = 0, SELECTED_SPELL = 1 }
enumerations.objectCategories = { PLAYER = 0, ACTOR = 1, PLACED_OBJECT = 2 }
enumerations.packetOrigin = { CLIENT_GAMEPLAY = 0, CLIENT_CONSOLE = 1, CLIENT_DIALOGUE = 2,
    CLIENT_SCRIPT_LOCAL = 3, CLIENT_SCRIPT_GLOBAL = 4, SERVER_SCRIPT = 5 }
enumerations.recordType = { ACTIVATOR = 0, APPARATUS = 1, ARMOR = 2, BODYPART = 3, BOOK = 4, CELL = 5, CLOTHING = 6,
    CONTAINER = 7, CREATURE = 8, DOOR = 9, ENCHANTMENT = 10, GAMESETTING = 11, INGREDIENT = 12, LIGHT = 13,
    LOCKPICK = 14, MISCELLANEOUS = 15, NPC = 16, POTION = 17, PROBE = 18, REPAIR = 19, SCRIPT = 20, SOUND = 21,
    SPELL = 22, STATIC = 23, WEAPON = 24 }
enumerations.resurrect = { REGULAR = 0, IMPERIAL_SHRINE = 1, TRIBUNAL_TEMPLE = 2 }
enumerations.spellbook = { SET = 0, ADD = 1, REMOVE = 2 }
enumerations.variableType = { SHORT = 0, LONG = 1, FLOAT = 2, INT = 3, STRING = 4 }
enumerations.weather = { CLEAR = 0, CLOUDY = 1, FOGGY = 2, OVERCAST = 3, RAIN = 4, THUNDER = 5, ASH = 6, BLIGHT = 7,
    SNOW = 8, BLIZZARD = 9 }

return enumerations
